<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZVdizxR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZVdizxR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZVdizxR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZVdizxR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZVdizxR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZVdizxR',
    'container.build_id' => '46a99f46',
    'container.build_time' => 1537349628,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZVdizxR');
