<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0hnBQM\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0hnBQM/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX0hnBQM.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX0hnBQM\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX0hnBQM\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X0hnBQM',
    'container.build_id' => '9d4f4716',
    'container.build_time' => 1537347580,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0hnBQM');
